# encoding:utf-8
import os

DEBUG = True
SERVER_PORT = 5000
SECRET_KEY = os.urandom(24)
SQLALCHEMY_TRACK_MODIFICATIONS = True

# DATABASE CONFIG for mysql
HOSTNAME = '10.67.118.210'
DB_PORT = '3306'
DATABASE = 'test'
USERNAME = 'root'
PASSWORD = 'password'
SQLALCHEMY_DATABASE_URI = 'mysql+mysqldb://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME, PASSWORD, HOSTNAME, DB_PORT, DATABASE)

# CACHE CONFIG for redis
REDIS_HOST = '10.67.118.210'
CACHE_TYPE = 'redis'
CACHE_REDIS_PORT = 6379
CACHE_REDIS_DB = 0
CACHE_REDIS_PASS = ""
REDIS_URL = "{}://:{}@{}:{}/{}".format(CACHE_TYPE, CACHE_REDIS_PASS, REDIS_HOST, CACHE_REDIS_PORT, CACHE_REDIS_DB)